---
title: "Class 12: Structural Bioinformatics (pt2)"
author: "Negin Silani"
date: "5/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Setup for Docking

we will first prepare our HIV-Pr system for drug docking by making a protein only PDB foramt file(i.e. we will remove water, existing ligand etc.)

```{r}
library(bio3d)
file<- get.pdb("1hsg")
```

```{r}
pdb<-read.pdb(file)
pdb
```

```{r}
prot<- atom.select(pdb, "protein", value= TRUE)
write.pdb(prot, file="1hsg_protein.pdb")
prot
```


```{r}
lig<- atom.select(pdb, "ligand", value= TRUE)
write.pdb(lig, file="1hsg_protein.pdb")
lig
```

we will load these into ADT to add hydrogens and make PDBQT files for each

Now we run autodoc vina with the cmd

/Downloads/autodock_vina_1_1_2_mac/bin/vina-- help

```{r}
library(bio3d)
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")
```

## Normal Mode analysis for flexibility prediciton

```{r}
pdb <- read.pdb("1hel")
modes <- nma( pdb )
m7 <- mktrj(modes, mode=7, file="mode_7.pdb")
```

